/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppMenu {
    }
    interface AppShell {
    }
    interface MyCard {
        "userName": string;
    }
    interface SearchWorld {
        "searchText": string;
    }
    interface TodoItem {
        "completed": boolean;
        "labelStyle": string;
        "todoId": number;
        "todoTitle": string;
    }
    interface TodoList {
        "newTitle": string;
    }
}
declare global {
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppShellElement extends Components.AppShell, HTMLStencilElement {
    }
    var HTMLAppShellElement: {
        prototype: HTMLAppShellElement;
        new (): HTMLAppShellElement;
    };
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLSearchWorldElement extends Components.SearchWorld, HTMLStencilElement {
    }
    var HTMLSearchWorldElement: {
        prototype: HTMLSearchWorldElement;
        new (): HTMLSearchWorldElement;
    };
    interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {
    }
    var HTMLTodoItemElement: {
        prototype: HTMLTodoItemElement;
        new (): HTMLTodoItemElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "app-menu": HTMLAppMenuElement;
        "app-shell": HTMLAppShellElement;
        "my-card": HTMLMyCardElement;
        "search-world": HTMLSearchWorldElement;
        "todo-item": HTMLTodoItemElement;
        "todo-list": HTMLTodoListElement;
    }
}
declare namespace LocalJSX {
    interface AppMenu {
    }
    interface AppShell {
    }
    interface MyCard {
        "userName"?: string;
    }
    interface SearchWorld {
        "onSearchWorldNameSelected"?: (event: CustomEvent<string>) => void;
        "searchText"?: string;
    }
    interface TodoItem {
        "completed"?: boolean;
        "labelStyle"?: string;
        "onDeleteTodo"?: (event: CustomEvent<number>) => void;
        "onToggleComplete"?: (event: CustomEvent<number>) => void;
        "todoId"?: number;
        "todoTitle"?: string;
    }
    interface TodoList {
        "newTitle"?: string;
    }
    interface IntrinsicElements {
        "app-menu": AppMenu;
        "app-shell": AppShell;
        "my-card": MyCard;
        "search-world": SearchWorld;
        "todo-item": TodoItem;
        "todo-list": TodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-shell": LocalJSX.AppShell & JSXBase.HTMLAttributes<HTMLAppShellElement>;
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "search-world": LocalJSX.SearchWorld & JSXBase.HTMLAttributes<HTMLSearchWorldElement>;
            "todo-item": LocalJSX.TodoItem & JSXBase.HTMLAttributes<HTMLTodoItemElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
        }
    }
}
